server:
  port: 9020
  tls_cert: ""
  tls_key: ""
  log_level: "info"
  max_header_bytes: 1048576

storage:
  type: "local"
  data_dir: "./data2"
  temp_dir: "./data2/tmp"
  meta_db: "./data2/meta.db"
  max_object_size: 5497558138880

auth:
  root_access_key: "minioadmin"
  root_secret_key: "minioadmin"
  allow_anonymous_read: false

ratelimit:
  enabled: true
  rps: 1000
  burst: 2000
  per_user_enabled: true
  per_user_rps: 100
  per_user_burst: 200

admin:
  ui_port: 9021
